name: New Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LS
        run: ls -la
      - name: Create export
        run: ./Godot_v4.5.1-stable_linux.x86_64 --headless --export-release "CI-Web" ./mine-defense/project.godot
      - name: Zip export
        run: zip -r mine-defense-release.zip mine-defense-release
      
