name: New Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*
    branch:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget zip unzip git tar
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: "mine-defense"
      - name: LOGGING
        run: pwd && ls -la
      - name: Create export
        run: ./Godot_v4.5.1-stable_linux.x86_64 --headless --export-release "CI-Web" ./mine-defense/project.godot
      - name: Zip export
        run: zip -r mine-defense-release.zip mine-defense-release
